---

- name: Change root password
  user:
    name: root
    password: "{{ common_root_password }}"

- name: Add deploy user
  user:
    name: "{{ common_deploy_username }}"
    password: "{{ common_deploy_password }}"
    shell: /sbin/nologin
    system: yes

- name: Add sudoers file
  template:
    src: ansible.j2
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Add authorized keys for deploy user
  authorized_key:
    user: "{{ common_deploy_username }}"
    key: "{{ common_deploy_key }}"
    state: present

- name: Install security packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ufw
    - unattended-upgrades
    - fail2ban

- name: Configure unattended-upgrades
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644

- name: Configure firewall for ssh
  ufw:
    policy: deny
    name: OpenSSH
    rule: allow
    state: enabled

- name: Configure ssh
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart ssh

- name: Create user
  user:
    name: "{{ common_user_username }}"
    password: "{{ common_user_password }}"
    groups: sudo
    append: yes

- name: Add authorized keys for user
  authorized_key:
    user: "{{ common_user_username }}"
    key: "{{ common_user_key }}"
    state: present
